version: "3.7"

services:
  nex-dashbaord-prod:
    env_file: .env.production
    environment:
      - REACT_APP_API_URL_PROD
    build:
      context: .
      dockerfile: Dockerfile
      args:
        api_url: $REACT_APP_API_URL_PROD
    ports:
      - "80:80"
